language: java
jdk:
    - oraclejdk8
group: stable
dist: trusty
os: linux
script: 
    - ./gradlew run
    - ./gradlew run --args="coordinatorTest"
    - ./gradlew run --args="coordinatorTestVisualization"
