language: java
jdk:
    - oraclejdk8
group: stable
dist: trusty
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
os: linux
script: 
# - ./gradlew run
    - ./gradlew run --args="-baking"
    - ./gradlew run --args="-packaging"
    - ./gradlew run --args="-baking -packaging"
# - ./gradlew run --args="-customer -orderProcessing -baking"
# - ./gradlew run --args="-customer -orderProcessing -packaging"
# - ./gradlew run --args="-customer -orderProcessing -baking -packaging"
